version: "3.8"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    env_file:
      #! En produccion cambiar las variables de entorno
      #- .env.production
      - .env
    volumes:
      - .:/app